config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # トップページ
  root "home#top"

  # アバウトページ
  get "/about" => "about#about"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  # アバウトページ
  def about
    #code
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # トップページ
  def top
    #code
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/about.html.erb
<div class="about-top">
  <h1>Otsuka Satoshi</h1>
</div>
<div class="about-bottom">
  <div class="container">
    <div class="about-flex">
      <div class="career">
        テキスト
      </div>
      <div class="intro">
        テキスト
      </div>
      <div class="skill">
        テキスト
      </div>
    </div>
  </div>
</div>

app/views/home/top.html.erb
<div id="top">
  <h1>"Hello, World."</h1>
  <div class="arrow-down">
    <div class="left"></div>
    <div class="right"></div>
  </div>
</div>
<%= render "shared/global_nav" %>
<div id="about">
  <div class="container">
    <h2>About</h2>
    <div class="wrap">
      <div class="image-box">
        <%= image_tag "portfolio.jpg" %>
      </div>
      <div class="text-box">
        <h3>OTSUKA SATOSHI</h3>
        <p>そのうちいろいろ書きます。</p>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>OTSUKA SATOSHI</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name=”keywords” content="OTSUKA SATOSHI,オオツカサトシ,おおつかさとし,大塚聡史"/>
    <meta name=”description” content="OTSUKA SATOSHI : Web Engineer"/>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="sns">
      <h4>Follow Me</h4>
      <ul class="icons">
        <li class="circle">
          <%= link_to "https://twitter.com/OtsukaSatoshi", rel: "noopener", target: "_blank" do %>
          <i class="fa fa-twitter" aria-hidden="true"></i>
          <% end %>
        </li>
        <li class="circle">
          <%= link_to "http://blog.otsukasatoshi.com", rel: "noopener", target: "_blank" do %>
          <i class="fa fa-rss" aria-hidden="true"></i>
          <% end %>
        </li>
        <li class="circle">
          <%= link_to "https://github.com/OtsukaSatoshi", rel: "noopener", target: "_blank" do %>
          <i class="fa fa-github" aria-hidden="true"></i>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="copyright">
      Copyright &copy; OTSUKA SATOSHI
    </div>
  </div>
</footer>

app/views/shared/_global_nav.html.erb
<div id="global-nav" class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <i class="fa fa-bars"></i>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <span>OTSUKA SATOSHI</span>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- ヘッダー右側 -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Works", "#" %></li>
        <li><%= link_to "SNS", "#" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</div>